[package]
name = "rusty"
version = "0.0.2"
authors = ["hexajohnny"]
edition = "2021"
build = "build.rs"

[dependencies]
anyhow = "1.0"
arboard = "3.4"
eframe = "0.26"
egui_tiles = "0.7.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ssh2 = "0.9"
vt100 = "0.15"
tray-icon = "0.19"
image = { version = "0.25", default-features = false, features = ["png"] }
crossbeam-channel = "0.5"
once_cell = "1.19"
rfd = "0.14"
base64 = "0.22"
windows-sys = { version = "0.52", features = ["Win32_Foundation", "Win32_Security_Cryptography"] }

[profile.release]
opt-level = "z"
lto = "fat"
codegen-units = 1
panic = "abort"
strip = "symbols"

[build-dependencies]
winres = "0.1"

[patch.crates-io]
vt100 = { path = "vendor/vt100" }
